CREATE TABLE HMG_STG.ODS_DBU_SIP_GRUPO_XML (
	SIP_COD_GRUPO   NUMBER(10,0),
	SIP_DESC_GRUPO  VARCHAR2(300 CHAR),
	SIP_TIP_GRUPO   VARCHAR2(1 CHAR),
	DT_CARGA        TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DBU_SIP_GRUPO_XML (
	SIP_COD_GRUPO   NUMBER(10,0),
	SIP_DESC_GRUPO  VARCHAR2(300 CHAR),
	SIP_TIP_GRUPO   VARCHAR2(1 CHAR),
	DT_CARGA        TIMESTAMP
) TABLESPACE TABS_DAT;