CREATE TABLE HMG_STG.ODS_DBU_ITEM_TAB (
	ITEM_COD NUMBER(10,0),
	TPTAB_COD NUMBER(10,0),
	TPTBV_COD CHAR(2),
	ITEMT_COD_PROC VARCHAR2(10 CHAR),
	ITEMT_DES VARCHAR2(200 CHAR),
	ITEMT_DAT_VIGEN DATE,
	ITEMT_DAT_INATIV DATE DEFAULT to_date('01010001','ddmmyyyy'),
	ITEMT_COD_GRUPO NUMBER(10,0),
	DT_CARGA TIMESTAMP,
	DT_DIGITACAO TIMESTAMP

) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DBU_ITEM_TAB (
	ITEM_COD NUMBER(10,0),
	TPTAB_COD NUMBER(10,0),
	TPTBV_COD CHAR(2),
	ITEMT_COD_PROC VARCHAR2(10 CHAR),
	ITEMT_DES VARCHAR2(200 CHAR),
	ITEMT_DAT_VIGEN DATE,
	ITEMT_DAT_INATIV DATE DEFAULT to_date('01010001','ddmmyyyy'),
	ITEMT_COD_GRUPO NUMBER(10,0),
	DT_CARGA TIMESTAMP,
	DT_DIGITACAO TIMESTAMP
) TABLESPACE TABS_DAT;