/*
    Foi excedido a quantidade de caracteres para o nome da tabela

     Antes: ODS_DTC_AUTSC2_HIS_SOLIC_ITENS_ERRO
    Depois: AUTSC2_HIS_SOLIC_ITENS_ERRO
*/

CREATE TABLE HMG_STG.AUTSC2_HIS_SOLIC_ITENS_ERRO (
    CD_SOLICITACAO          NUMBER(30,0)
    , NR_VERSAO             NUMBER
    , NR_SEQ_ITEM           NUMBER(38,0)
    , ERRO_COD              NUMBER
    , CD_SITUACAO_ITEM      NUMBER
    , DS_MSG_ERRO_ADICIONAL VARCHAR2(300 CHAR)
    , DT_DIGITACAO          TIMESTAMP
    , DT_CARGA              TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.AUTSC2_HIS_SOLIC_ITENS_ERRO (
    CD_SOLICITACAO          NUMBER(30,0)
    , NR_VERSAO             NUMBER
    , NR_SEQ_ITEM           NUMBER(38,0)
    , ERRO_COD              NUMBER
    , CD_SITUACAO_ITEM      NUMBER
    , DS_MSG_ERRO_ADICIONAL VARCHAR2(300 CHAR)
    , DT_DIGITACAO          TIMESTAMP
    , DT_CARGA              TIMESTAMP
) TABLESPACE TABS_DAT;

TRUNCATE TABLE HMG_STG.AUTSC2_HIS_SOLIC_ITENS_ERRO;
TRUNCATE TABLE PRD_STG.AUTSC2_HIS_SOLIC_ITENS_ERRO;
