CREATE TABLE HMG_STG.ODS_DBU_TIPPR (
	TIPPR_COD NUMBER(10,0),
	TIPPR_NOM_TIPO VARCHAR2(255 CHAR),
	DT_CARGA TIMESTAMP
                                   ) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DBU_TIPPR (
	TIPPR_COD NUMBER(10,0),
	TIPPR_NOM_TIPO VARCHAR2(255 CHAR),
	DT_CARGA TIMESTAMP
                                   ) TABLESPACE TABS_DAT;