CREATE TABLE HMG_STG.ODS_DBU_UNIMED (
	UNI_COD NUMBER(4,0),
	UNI_COD_FED NUMBER(4,0),
	UNI_COD_CONFED NUMBER(4,0),
	UNI_IND VARCHAR2(1 CHAR),
	UNI_IND_MOT_EXCL VARCHAR2(2 CHAR),
	UNI_PES_COD NUMBER(10,0),
	UNI_NRO_REG NUMBER(10,0),
	UNI_DAT_FUND DATE,
	UNI_DAT_EXCL DATE,
	UNI_IND_DAT_TAXA_INTERC VARCHAR2(1 CHAR) DEFAULT 'A' ,
	UNI_SAC_TELEFONE VARCHAR2(20 CHAR),
	UNI_SAC_SITE VARCHAR2(200 CHAR),
	UNI_OUVIDORIA_TELEFONE VARCHAR2(20 CHAR),
	UNI_COMPART VARCHAR2(1 CHAR),
	UNI_FLG_POSSUI_COMPART_NEG_CO VARCHAR2(1 CHAR),
	UNI_FLG_ACEITA_A100_SEM_VALID VARCHAR2(1 CHAR),
	DT_CARGA TIMESTAMP
                              ) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DBU_UNIMED (
	UNI_COD NUMBER(4,0),
	UNI_COD_FED NUMBER(4,0),
	UNI_COD_CONFED NUMBER(4,0),
	UNI_IND VARCHAR2(1 CHAR),
	UNI_IND_MOT_EXCL VARCHAR2(2 CHAR),
	UNI_PES_COD NUMBER(10,0),
	UNI_NRO_REG NUMBER(10,0),
	UNI_DAT_FUND DATE,
	UNI_DAT_EXCL DATE,
	UNI_IND_DAT_TAXA_INTERC VARCHAR2(1 CHAR) DEFAULT 'A' ,
	UNI_SAC_TELEFONE VARCHAR2(20 CHAR),
	UNI_SAC_SITE VARCHAR2(200 CHAR),
	UNI_OUVIDORIA_TELEFONE VARCHAR2(20 CHAR),
	UNI_COMPART VARCHAR2(1 CHAR),
	UNI_FLG_POSSUI_COMPART_NEG_CO VARCHAR2(1 CHAR),
	UNI_FLG_ACEITA_A100_SEM_VALID VARCHAR2(1 CHAR),
	DT_CARGA TIMESTAMP
                              ) TABLESPACE TABS_DAT;