CREATE TABLE HMG_STG.FLT_AUDITORIA_AUTORIZATIVA (
 	CD_SOLICITACAO					NUMBER(30,0)
	, CD_SOLICITACAO_PAI			NUMBER
	, NU_GUIA						VARCHAR2(20 CHAR)
	, DT_SOLICITACAO				DATE
	, DT_DIGITACAO					DATE
	, NR_VERSAO_HIS					NUMBER
	, DT_ALTERACAO_HIS				DATE
	, TP_SOLICITACAO				NUMBER(1,0)
	, CD_TIPO_SOLICITACAO 			NUMBER(30,0)
	, TIPO_SOLICITACAO				VARCHAR2(20 CHAR)
	, CD_UNIMED_SOLICITANTE			VARCHAR2(5 CHAR)
	, UNIMED_SOLICITANTE			VARCHAR2(100 CHAR)
	, CD_CARATER_SOLICITACAO		NUMBER(1,0)
	, DESC_CARATER_SOLICITACAO		VARCHAR2(255 CHAR)
	, CD_BANDEJA					NUMBER
	, DS_BANDEJA					VARCHAR2(255 CHAR)
	, NM_ACAO						VARCHAR2(255 CHAR)
	, CD_USUARIO_AUDITOR			NUMBER
	, NOME_AUDITOR					VARCHAR2(70 CHAR)
	, CD_GRUPO_AUDITOR 				NUMBER(38 ,0)
	, NM_GRUPO_AUDITOR 				VARCHAR2(200 CHAR)
	, CD_USUARIO_ALTERACAO			NUMBER
	, USUARIO_ALTERACAO				VARCHAR2(70 CHAR)
	, CD_SITUACAO					NUMBER
	, DESCRICAO_SITUACAO			VARCHAR2(255 CHAR)
	, REDE_AUTORIZADA				VARCHAR2(20 CHAR)
	, APROVACAO_AUTOMATICA			VARCHAR2(5 CHAR)
	, CD_ATENDIMENTO				VARCHAR2(2 CHAR)
	, TIPO_ATENDIMENTO				VARCHAR2(255 CHAR)
	, CD_TIPO_INTERNACAO 			VARCHAR2(10 CHAR)
	, DESCRICAO_TIPO_INTERNACAO		VARCHAR2(255 CHAR)
	, CD_REGIME_INTERNACAO 			VARCHAR2(10 CHAR)
	, DESCRICAO_REGIME_INTERNACAO	VARCHAR2(255 CHAR)
	, CD_ACOMODACAO					NUMBER(2,0)
	, DESCRICAO_ACOMODACAO			VARCHAR2(120 CHAR)
	, ORIGEM						VARCHAR2(15 CHAR)
	, CD_TIPO_ENTRADA				NUMBER(1,0)
	, TIPO_ENTRADA 					VARCHAR2(40 CHAR)
	, NR_PRAZO_RN259				NUMBER(5,0)
	, DT_INICIO_PRAZO				DATE
	, CODIGO_CARTAO					VARCHAR2(20 CHAR)
    , BNF_ID                        NUMBER(12,0)
    , CD_COD_PESSOA_BENEF           NUMBER(10,0)
	, NOME_BENEFICIARIO				VARCHAR2(70 CHAR)
	, TIPO_BNFRIO_ATENDIDO			VARCHAR2(30 CHAR)
	, CODIGO_CONTRATO				NUMBER(10,0)
    , DT_INICIO_VIGENCIA_CONTRATO   TIMESTAMP
    , DT_EXCLUSAO_CONTRATO          TIMESTAMP
    , CD_UNIMED_BENEF               VARCHAR2(5 CHAR)
    , UNIMED_BENEFICIARIO           VARCHAR2(500 CHAR)
	, CD_CID						VARCHAR2(4 CHAR)
	, DESCRICAO_CID					VARCHAR2(100 CHAR)
	, CD_ITEM_PROC					VARCHAR2(10 CHAR)
	, ITEMT_DES						VARCHAR2(200 CHAR)
	, QTDE_PROCED_SOLICITADA		NUMBER(12,4)
	, QTDE_PROCED_AUTORIZADA		NUMBER(12,4)
	, CD_PREST_SOLIC				NUMBER(30,0)
	, CONTRATADO_SOLICITANTE		VARCHAR2(255 CHAR)
	, CPF_CNPJ_PRESTADOR 			VARCHAR2(50 CHAR)
	, CD_ESPECIALIDADE_PRESTADOR	NUMBER
	, DESCRICAO_ESPEC_PRESTADOR		VARCHAR2(30 CHAR)
	, TP_BNFRIO_ATEND				VARCHAR2(30 CHAR)
	, DT_APROVACAO					DATE
	, REGULADA						VARCHAR2(5 CHAR)
    , CD_GRUPO_PRESTADOR            NUMBER(6, 0)
    , DS_GRUPO_PRESTADOR            VARCHAR2(40 CHAR)
    , CD_TIPO_PRESTADOR             NUMBER(10, 0)
    , DS_TIPO_PRESTADOR             VARCHAR2(255 CHAR)
	, NU_CRM						NUMBER(15, 0)
	, DT_INICIO						TIMESTAMP
	, DT_FIM						TIMESTAMP
	, TEMPO_AUDITORIA_MIN			NUMBER(30, 2)
	, DT_CARGA						TIMESTAMP
) TABLESPACE TABS_DAT;

GRANT SELECT ON HMG_STG.FLT_AUDITORIA_AUTORIZATIVA TO USER_BI_DEV;


CREATE TABLE PRD_STG.FLT_AUDITORIA_AUTORIZATIVA(
    CD_SOLICITACAO					NUMBER(30,0)
	, CD_SOLICITACAO_PAI			NUMBER
	, NU_GUIA						VARCHAR2(20 CHAR)
	, DT_SOLICITACAO				DATE
	, DT_DIGITACAO					DATE
	, NR_VERSAO_HIS					NUMBER
	, DT_ALTERACAO_HIS				DATE
	, TP_SOLICITACAO				NUMBER(1,0)
	, CD_TIPO_SOLICITACAO 			NUMBER(30,0)
	, TIPO_SOLICITACAO				VARCHAR2(20 CHAR)
	, CD_UNIMED_SOLICITANTE			VARCHAR2(5 CHAR)
	, UNIMED_SOLICITANTE			VARCHAR2(100 CHAR)
	, CD_CARATER_SOLICITACAO		NUMBER(1,0)
	, DESC_CARATER_SOLICITACAO		VARCHAR2(255 CHAR)
	, CD_BANDEJA					NUMBER
	, DS_BANDEJA					VARCHAR2(255 CHAR)
	, NM_ACAO						VARCHAR2(255 CHAR)
	, CD_USUARIO_AUDITOR			NUMBER
	, NOME_AUDITOR					VARCHAR2(70 CHAR)
	, CD_GRUPO_AUDITOR 				NUMBER(38 ,0)
	, NM_GRUPO_AUDITOR 				VARCHAR2(200 CHAR)
	, CD_USUARIO_ALTERACAO			NUMBER
	, USUARIO_ALTERACAO				VARCHAR2(70 CHAR)
	, CD_SITUACAO					NUMBER
	, DESCRICAO_SITUACAO			VARCHAR2(255 CHAR)
	, REDE_AUTORIZADA				VARCHAR2(20 CHAR)
	, APROVACAO_AUTOMATICA			VARCHAR2(5 CHAR)
	, CD_ATENDIMENTO				VARCHAR2(2 CHAR)
	, TIPO_ATENDIMENTO				VARCHAR2(255 CHAR)
	, CD_TIPO_INTERNACAO 			VARCHAR2(10 CHAR)
	, DESCRICAO_TIPO_INTERNACAO		VARCHAR2(255 CHAR)
	, CD_REGIME_INTERNACAO 			VARCHAR2(10 CHAR)
	, DESCRICAO_REGIME_INTERNACAO	VARCHAR2(255 CHAR)
	, CD_ACOMODACAO					NUMBER(2,0)
	, DESCRICAO_ACOMODACAO			VARCHAR2(120 CHAR)
	, ORIGEM						VARCHAR2(15 CHAR)
	, CD_TIPO_ENTRADA				NUMBER(1,0)
	, TIPO_ENTRADA 					VARCHAR2(40 CHAR)
	, NR_PRAZO_RN259				NUMBER(5,0)
	, DT_INICIO_PRAZO				DATE
	, CODIGO_CARTAO					VARCHAR2(20 CHAR)
    , BNF_ID                        NUMBER(12,0)
    , CD_COD_PESSOA_BENEF           NUMBER(10,0)
	, NOME_BENEFICIARIO				VARCHAR2(70 CHAR)
	, TIPO_BNFRIO_ATENDIDO			VARCHAR2(30 CHAR)
	, CODIGO_CONTRATO				NUMBER(10,0)
    , DT_INICIO_VIGENCIA_CONTRATO   TIMESTAMP
    , DT_EXCLUSAO_CONTRATO          TIMESTAMP
    , CD_UNIMED_BENEF               VARCHAR2(5 CHAR)
    , UNIMED_BENEFICIARIO           VARCHAR2(500 CHAR)
	, CD_CID						VARCHAR2(4 CHAR)
	, DESCRICAO_CID					VARCHAR2(100 CHAR)
	, CD_ITEM_PROC					VARCHAR2(10 CHAR)
	, ITEMT_DES						VARCHAR2(200 CHAR)
	, QTDE_PROCED_SOLICITADA		NUMBER(12,4)
	, QTDE_PROCED_AUTORIZADA		NUMBER(12,4)
	, CD_PREST_SOLIC				NUMBER(30,0)
	, CONTRATADO_SOLICITANTE		VARCHAR2(255 CHAR)
	, CPF_CNPJ_PRESTADOR 			VARCHAR2(50 CHAR)
	, CD_ESPECIALIDADE_PRESTADOR	NUMBER
	, DESCRICAO_ESPEC_PRESTADOR		VARCHAR2(30 CHAR)
	, TP_BNFRIO_ATEND				VARCHAR2(30 CHAR)
	, DT_APROVACAO					DATE
	, REGULADA						VARCHAR2(5 CHAR)
    , CD_GRUPO_PRESTADOR            NUMBER(6, 0)
    , DS_GRUPO_PRESTADOR            VARCHAR2(40 CHAR)
    , CD_TIPO_PRESTADOR             NUMBER(10, 0)
    , DS_TIPO_PRESTADOR             VARCHAR2(255 CHAR)
	, NU_CRM						NUMBER(15, 0)
	, DT_INICIO						TIMESTAMP
	, DT_FIM						TIMESTAMP
	, TEMPO_AUDITORIA_MIN			NUMBER(30, 2)
	, DT_CARGA						TIMESTAMP
) TABLESPACE TABS_DAT;

GRANT SELECT ON PRD_STG.FLT_AUDITORIA_AUTORIZATIVA TO USER_BI_DEV;