CREATE TABLE HMG_STG.ODS_DTC_CM_ATEND_EXEC (
    CD_CM_ATEND_EXEC       NUMBER(20, 0),
    CD_USUARIO             NUMBER(20, 0),
    DT_ATEND_EXEC          DATE         DEFAULT sysdate,
    CD_LOCAL               NUMBER(20, 0),
    CD_CM_PREST_EXEC       NUMBER(20, 0),
    FG_FINALIZADO          NUMBER(1, 0) DEFAULT 0,
    DT_FINALIZADO          DATE,
    FG_BIOMETRIA           NUMBER(1, 0) DEFAULT 0,
    FG_EXEC_PARCIAL        NUMBER(1, 0) DEFAULT 0,
    DT_ATEND_CONSULTA      DATE,
    TP_IDENT_CAPTURA_BNF   NUMBER(1, 0),
    CD_ESPEC_PREST_EXEC    NUMBER(4, 0),
    CD_CBOS_PREST_EXEC     NUMBER(6, 0),
    FG_CAPTURA_PJ_LIBERA   CHAR(1),
    FG_BIOMETRIA_HISTORICO NUMBER(1, 0),
    TP_BIOMETRIA_EXEC      NUMBER(1, 0),
    DT_CARGA               TIMESTAMP
) TABLESPACE TABS_DAT;


CREATE TABLE PRD_STG.ODS_DTC_CM_ATEND_EXEC (
    CD_CM_ATEND_EXEC       NUMBER(20, 0),
    CD_USUARIO             NUMBER(20, 0),
    DT_ATEND_EXEC          DATE         DEFAULT sysdate,
    CD_LOCAL               NUMBER(20, 0),
    CD_CM_PREST_EXEC       NUMBER(20, 0),
    FG_FINALIZADO          NUMBER(1, 0) DEFAULT 0,
    DT_FINALIZADO          DATE,
    FG_BIOMETRIA           NUMBER(1, 0) DEFAULT 0,
    FG_EXEC_PARCIAL        NUMBER(1, 0) DEFAULT 0,
    DT_ATEND_CONSULTA      DATE,
    TP_IDENT_CAPTURA_BNF   NUMBER(1, 0),
    CD_ESPEC_PREST_EXEC    NUMBER(4, 0),
    CD_CBOS_PREST_EXEC     NUMBER(6, 0),
    FG_CAPTURA_PJ_LIBERA   CHAR(1),
    FG_BIOMETRIA_HISTORICO NUMBER(1, 0),
    TP_BIOMETRIA_EXEC      NUMBER(1, 0),
    DT_CARGA               TIMESTAMP
) TABLESPACE TABS_DAT;


