CREATE TABLE HMG_STG.ODS_SGU_DBU_CID10 (
	CID10_COD VARCHAR2(7 CHAR),
	CID10_DES VARCHAR2(100 CHAR),
	CID10_DAT_INATIVACAO DATE,
	DT_CARGA DATE
)
TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_SGU_DBU_CID10 (
	CID10_COD VARCHAR2(7 CHAR),
	CID10_DES VARCHAR2(100 CHAR),
	CID10_DAT_INATIVACAO DATE,
	DT_CARGA DATE
)
TABLESPACE TABS_DAT;