CREATE TABLE HMG_STG.ODS_DBU_CM_DOMINIOS (
	CD_DOMINIO NUMBER(20,0),
	NM_DOMINIO VARCHAR2(70 CHAR),
	DS_VALOR VARCHAR2(10 CHAR),
	DS_MASCARA_VALOR VARCHAR2(255 CHAR),
	DS_EXPLICACAO VARCHAR2(255 CHAR),
	DT_CARGA TIMESTAMP
)
TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DBU_CM_DOMINIOS (
	CD_DOMINIO NUMBER(20,0),
	NM_DOMINIO VARCHAR2(70 CHAR),
	DS_VALOR VARCHAR2(10 CHAR),
	DS_MASCARA_VALOR VARCHAR2(255 CHAR),
	DS_EXPLICACAO VARCHAR2(255 CHAR),
	DT_CARGA TIMESTAMP
)
TABLESPACE TABS_DAT;