CREATE TABLE HMG_STG.ODS_DTC_SCE_CFG_DOMINIOS (
	NM_DOMINIO		VARCHAR2(40 CHAR)
	, VL_DOMINIO	VARCHAR2(20 CHAR)
	, DS_DOMINIO	VARCHAR2(120 CHAR)
	, DT_CARGA		TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_SCE_CFG_DOMINIOS (
	NM_DOMINIO		VARCHAR2(40 CHAR)
	, VL_DOMINIO	VARCHAR2(20 CHAR)
	, DS_DOMINIO	VARCHAR2(120 CHAR)
	, DT_CARGA		TIMESTAMP
) TABLESPACE TABS_DAT;

TRUNCATE TABLE HMG_STG.ODS_DTC_SCE_CFG_DOMINIOS;
TRUNCATE TABLE PRD_STG.ODS_DTC_SCE_CFG_DOMINIOS;
