CREATE TABLE HMG_STG.CONTROL_TABLE(
    CD_CARGA            INT NOT NULL
    , NO_TABELA         VARCHAR2(100 CHAR)
    , DT_INICIO         TIMESTAMP
    , DT_FIM            TIMESTAMP
    , DT_PARAMETRO      TIMESTAMP
    , NU_DIAS_DELTA     INT
    , FL_ATIVO          CHAR(1)
    , CONSTRAINT CONTROL_TABLE_PK PRIMARY KEY (CD_CARGA)
    USING INDEX (
        CREATE UNIQUE INDEX HMG_STG.CONTROL_TABLE
            ON HMG_STG.CONTROL_TABLE (CD_CARGA ASC)
                TABLESPACE TABS_IDX
    ) ENABLE
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.CONTROL_TABLE(
    CD_CARGA            INT NOT NULL
    , NO_TABELA         VARCHAR2(100 CHAR)
    , DT_INICIO         TIMESTAMP
    , DT_FIM            TIMESTAMP
    , DT_PARAMETRO      TIMESTAMP
    , NU_DIAS_DELTA     INT
    , FL_ATIVO          CHAR(1)
    , CONSTRAINT CONTROL_TABLE_PK PRIMARY KEY (CD_CARGA)
    USING INDEX (
        CREATE UNIQUE INDEX PRD_STG.CONTROL_TABLE
            ON PRD_STG.CONTROL_TABLE (CD_CARGA ASC)
                TABLESPACE TABS_IDX
    ) ENABLE
) TABLESPACE TABS_DAT;
