CREATE TABLE HMG_STG.ODS_DTC_CM_DOMINIOS (
	CD_DOMINIO NUMBER(20,0),
	NM_DOMINIO VARCHAR2(70 CHAR),
	DS_VALOR VARCHAR2(30 CHAR),
	DS_MASCARA_VALOR VARCHAR2(255 CHAR),
	DS_EXPLICACAO VARCHAR2(255 CHAR),
	NR_VERSAO VARCHAR2(7 CHAR),
	DT_CARGA TIMESTAMP
)
TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_CM_DOMINIOS (
	CD_DOMINIO NUMBER(20,0),
	NM_DOMINIO VARCHAR2(70 CHAR),
	DS_VALOR VARCHAR2(30 CHAR),
	DS_MASCARA_VALOR VARCHAR2(255 CHAR),
	DS_EXPLICACAO VARCHAR2(255 CHAR),
	NR_VERSAO VARCHAR2(7 CHAR),
	DT_CARGA TIMESTAMP
)
TABLESPACE TABS_DAT;