CREATE TABLE HMG_STG.ODS_DTC_AUTSC2_DOMINIOS (
	NM_DOMINIO 	 	VARCHAR2(40 CHAR)
	, VL_DOMINIO	VARCHAR2(40 CHAR)
	, DS_DOMINIO 	VARCHAR2(150 CHAR)
	, NR_VERSAO 	VARCHAR2(7 CHAR)
	, DT_CARGA		TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_AUTSC2_DOMINIOS (
	NM_DOMINIO 	 	VARCHAR2(40 CHAR)
	, VL_DOMINIO	VARCHAR2(40 CHAR)
	, DS_DOMINIO 	VARCHAR2(150 CHAR)
	, NR_VERSAO 	VARCHAR2(7 CHAR)
	, DT_CARGA		TIMESTAMP
) TABLESPACE TABS_DAT;

TRUNCATE TABLE HMG_STG.ODS_DTC_AUTSC2_DOMINIOS;
TRUNCATE TABLE PRD_STG.ODS_DTC_AUTSC2_DOMINIOS;
