CREATE TABLE HMG_STG.ODS_DTC_AUTSC2_SITUACOES_SOLIC (
	CD_SITUACAO NUMBER,
	NM_SITUACAO VARCHAR2(255 CHAR),
	FG_MOSTRA_SENHA NUMBER(1,0) DEFAULT 0,
	DT_CARGA TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_AUTSC2_SITUACOES_SOLIC (
	CD_SITUACAO NUMBER,
	NM_SITUACAO VARCHAR2(255 CHAR),
	FG_MOSTRA_SENHA NUMBER(1,0) DEFAULT 0,
	DT_CARGA TIMESTAMP
) TABLESPACE TABS_DAT;
