CREATE TABLE HMG_STG.ODS_DTC_ERRO
(
    ERRO_COD      NUMBER(30, 0),
    ERRO_DES      VARCHAR2(150 CHAR),
    ERRO_TIP      VARCHAR2(1 CHAR),
    ERRO_COD_PTU  NUMBER(30, 0),
    TP_ERRO_AUTSC VARCHAR2(1 CHAR),
    TP_ERRO_XML   VARCHAR2(1 CHAR),
    DT_CARGA TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_ERRO
(
    ERRO_COD      NUMBER(30, 0),
    ERRO_DES      VARCHAR2(150 CHAR),
    ERRO_TIP      VARCHAR2(1 CHAR),
    ERRO_COD_PTU  NUMBER(30, 0),
    TP_ERRO_AUTSC VARCHAR2(1 CHAR),
    TP_ERRO_XML   VARCHAR2(1 CHAR),
    DT_CARGA TIMESTAMP

) TABLESPACE TABS_DAT;