CREATE TABLE HMG_STG.ODS_DTC_AUTSC2_HIS_SOLIC_ERRO (
	CD_SOLICITACAO          	NUMBER(30,0)
	, NR_VERSAO               	NUMBER(30,0)
	, ERRO_COD               	NUMBER(30,0)
	, CD_SITUACAO_ITEM        	NUMBER(30,0)
	, DS_MSG_ERRO_ADICIONAL   	VARCHAR2(300 CHAR)
	, DT_CARGA					TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_AUTSC2_HIS_SOLIC_ERRO (
	CD_SOLICITACAO          	NUMBER(30,0)
	, NR_VERSAO               	NUMBER(30,0)
	, ERRO_COD               	NUMBER(30,0)
	, CD_SITUACAO_ITEM        	NUMBER(30,0)
	, DS_MSG_ERRO_ADICIONAL   	VARCHAR2(300 CHAR)
	, DT_CARGA					TIMESTAMP
) TABLESPACE TABS_DAT;