CREATE TABLE HMG_STG.ODS_DTC_AUTSC2_GRUPOS (
	CD_GRUPO    NUMBER,
	NM_GRUPO    VARCHAR2(100 CHAR),
	DT_CARGA    TIMESTAMP
) TABLESPACE TABS_DAT;


CREATE TABLE PRD_STG.ODS_DTC_AUTSC2_GRUPOS (
	CD_GRUPO    NUMBER,
	NM_GRUPO    VARCHAR2(100 CHAR),
	DT_CARGA    TIMESTAMP
) TABLESPACE TABS_DAT;