CREATE TABLE HMG_STG.ODS_DTC_AUTSC2_NIVEIS_ATEND (
	CD_NIVEL                NUMBER,
	NM_NIVEL                VARCHAR2(255 CHAR),
	CD_UNIMED_ATENDE        NUMBER(4,0),
	FG_PARTIC_DISTRIBUICAO  NUMBER(1,0),
	NR_PRIORIDADE           NUMBER(10,0),
	DT_CARGA                TIMESTAMP
) TABLESPACE TABS_DAT;

CREATE TABLE PRD_STG.ODS_DTC_AUTSC2_NIVEIS_ATEND (
	CD_NIVEL                NUMBER,
	NM_NIVEL                VARCHAR2(255 CHAR),
	CD_UNIMED_ATENDE        NUMBER(4,0),
	FG_PARTIC_DISTRIBUICAO  NUMBER(1,0),
	NR_PRIORIDADE           NUMBER(10,0),
	DT_CARGA                TIMESTAMP
) TABLESPACE TABS_DAT;