CREATE TABLE HMG_STG.ODS_DTC_CM_TISS_GUIA (
    CD_TISS_GUIA                  NUMBER(20, 0),
    TP_GUIA                       NUMBER(1, 0),
    NR_REG_ANS                    VARCHAR2(6 CHAR),
    NR_GUIA                       VARCHAR2(20 CHAR),
    NR_GUIA_PRINCIPAL             VARCHAR2(20 CHAR),
    DT_AUTORIZACAO                DATE,
    NR_SENHA                      VARCHAR2(20 CHAR),
    DT_VALIDADE_SENHA             DATE,
    DT_HR_EMISSAO                 DATE,
    DT_HR_INCLUSAO                DATE,
    CD_CARTAO_BNF                 VARCHAR2(21 CHAR),
    NM_PLANO_BNF                  VARCHAR2(60 CHAR),
    DT_VALIDADE_CARTEIRA_BNF      DATE,
    NM_COMPLETO_BNF               VARCHAR2(70 CHAR),
    NR_CNS_BNF                    VARCHAR2(20 CHAR),
    CD_PREST_SOLIC                NUMBER(20, 0),
    NM_PREST_SOLIC                VARCHAR2(70 CHAR),
    CD_CNES_SOLIC                 NUMBER(7, 0),
    NM_PROFIS_SOLIC               VARCHAR2(70 CHAR),
    TP_CONSELHO_SOLIC             VARCHAR2(7 CHAR),
    NR_CONSELHO_SOLIC_OLD         NUMBER(15, 0),
    SG_UF_CONSELHO_SOLIC          VARCHAR2(2 CHAR),
    CD_CBOS_SOLIC                 VARCHAR2(10 CHAR),
    DT_HR_SOLIC                   DATE,
    TP_ATENDIMENTO                VARCHAR2(2 CHAR),
    TP_CARATER                    VARCHAR2(1 CHAR),
    DS_INDICACAO_CLINICA          VARCHAR2(500 CHAR),
    CD_OPERADORA_EXEC             NUMBER,
    NM_OPERADORA_EXEC             VARCHAR2(70 CHAR),
    CD_CNES_OPERADORA_EXEC        NUMBER,
    CD_PRESTADOR_EXEC             NUMBER(14, 0),
    NM_PRESTADOR_EXEC             VARCHAR2(70 CHAR),
    TP_LOGRADOURO_EXEC            VARCHAR2(3 CHAR),
    DS_LOGRADOURO_EXEC            VARCHAR2(50 CHAR),
    NR_LOGRADOURO_EXEC            VARCHAR2(5 CHAR),
    DS_COMPLEMENTO_EXEC           VARCHAR2(40 CHAR),
    NM_MUNICIPIO_EXEC             VARCHAR2(120 CHAR),
    SG_UF_EXEC                    VARCHAR2(2 CHAR),
    CD_IBGE_MUNICIPIO_EXEC        VARCHAR2(7 CHAR),
    NR_CEP_EXEC                   VARCHAR2(8 CHAR),
    CD_CNES_EXEC                  VARCHAR2(7 CHAR),
    CD_PARTICIPACAO_EXEC          VARCHAR2(2 CHAR),
    NM_PROFISSIONAL_EXEC          VARCHAR2(70 CHAR),
    TP_CONSELHO_EXEC              VARCHAR2(7 CHAR),
    NR_CONSELHO_EXEC_OLD          NUMBER(15, 0),
    SG_UF_CONSELHO_EXEC           VARCHAR2(2 CHAR),
    NR_CPF_EXEC                   NUMBER(14, 0),
    CD_CBOS_EXEC                  VARCHAR2(10 CHAR),
    TP_DOENCA                     VARCHAR2(1 CHAR),
    NR_TMP_DOENCA                 NUMBER(3, 0),
    DM_TMP_DOENCA                 VARCHAR2(1 CHAR),
    TP_ACIDENTE                   NUMBER(1, 0),
    DT_HR_ATENDIMENTO             DATE,
    TP_CONSULTA                   VARCHAR2(1 CHAR),
    TP_SAIDA_CONSULTA             VARCHAR2(1 CHAR),
    DS_OBSERVACAO                 VARCHAR2(500 CHAR),
    VL_TOTAL_PROCEDIMENTO         NUMBER(9, 2),
    VL_TOTAL_TAXA_ALUGUEL         NUMBER(9, 2),
    VL_TOTAL_MATERIAL             NUMBER(9, 2),
    VL_TOTAL_MEDICAMENTO          NUMBER(9, 2),
    VL_TOTAL_DIARIA               NUMBER(9, 2),
    VL_TOTAL_TAXAS_DIVERSAS       NUMBER(9, 2),
    VL_TOTAL_GASES_MED            NUMBER(9, 2),
    VL_TOTAL_OPM                  NUMBER(9, 2),
    VL_TOTAL_GUIA                 NUMBER(9, 2),
    CD_MOTIVO_SAIDA               VARCHAR2(2 CHAR),
    NR_SOLIC                      NUMBER(20, 0),
    DT_HR_ALTA                    DATE,
    TP_ACOMODACAO                 NUMBER(2, 0),
    TP_OBSTET_GESTACAO            VARCHAR2(1 CHAR),
    TP_OBSTET_ABORTO              VARCHAR2(1 CHAR),
    TP_OBSTET_TRANST_MATERNO      VARCHAR2(1 CHAR),
    TP_OBSTET_COMPLIC_PUERPERIO   VARCHAR2(1 CHAR),
    TP_OBSTET_ATENDIMENTO_RN      VARCHAR2(1 CHAR),
    TP_OBSTET_COMPLIC_NEONATAL    VARCHAR2(1 CHAR),
    TP_OBSTET_BAIXO_PESO          VARCHAR2(1 CHAR),
    TP_OBSTET_CESAREA             VARCHAR2(1 CHAR),
    TP_OBSTET_NORMAL              VARCHAR2(1 CHAR),
    DM_CD_OBITO_MULHER            NUMBER(1, 0),
    QT_NASCIDO_VIVO               NUMBER(2, 0),
    QT_NASCIDO_PREMATURO          NUMBER(2, 0),
    NR_DECLARACAO_NASC_VIVO       VARCHAR2(15 CHAR),
    QT_OBITO_PRECOCE              NUMBER(2, 0),
    QT_OBITO_TARDIO               NUMBER(2, 0),
    QT_NASCIDO_MORTO              NUMBER(2, 0),
    TP_INTERNACAO                 NUMBER,
    NR_DECLARACAO_OBITO           VARCHAR2(12 CHAR),
    DM_REGIME_INTERNACAO          NUMBER(1, 0),
    DM_TP_FATURAMENTO             VARCHAR2(1 CHAR),
    DT_ENTRADA                    DATE,
    TP_ORIGEM                     NUMBER(1, 0),
    TP_SITUACAO                   NUMBER(2, 0),
    CD_LOCAL_ATENDIMENTO          NUMBER(20, 0),
    CD_USUARIO                    NUMBER(20, 0),
    CD_TISS_GUIA_PRINCIPAL        NUMBER(20, 0),
    CD_CARTAO_UNIMED_BNF          NUMBER(4, 0),
    CD_CARTAO_PLANO_BNF           NUMBER(4, 0),
    CD_CARTAO_BENEF_BNF           NUMBER(6, 0),
    CD_CARTAO_DEPEN_BNF           NUMBER(2, 0),
    DT_PROC_PRECIF                DATE,
    DT_PROC_AUDIT                 DATE,
    CD_GUIA_SCCARD                NUMBER(20, 0),
    CD_ARQUIVO_TISS               NUMBER(20, 0),
    CD_UNIMED_EXEC                NUMBER(4, 0),
    DT_PROC_CAMARA                DATE,
    DM_CLASSIFICACAO_SOLIC        NUMBER(5, 0),
    NR_SENHA_GESTAO               VARCHAR2(20 CHAR),
    DT_PROC_ENTREGA               DATE,
    FG_ALTERACAO                  NUMBER(1, 0),
    DT_AJUSTE_VIA_ACESSO          DATE,
    DT_TROCA_DESC_ITENS           DATE,
    NR_VERSAO_TISS                VARCHAR2(7 CHAR),
    FG_VALID_IMPORT_ATIVA         NUMBER(1, 0),
    FG_ATENDIMENTO_RN             VARCHAR2(1 CHAR),
    NR_GUIA_PRESTADOR             VARCHAR2(20 CHAR),
    FG_OBITO_RN                   VARCHAR2(1 CHAR),
    NR_VERSAO_GUIA_IMPORT         VARCHAR2(7 CHAR),
    CD_PROTOCOLO                  NUMBER,
    NR_LOTE                       NUMBER(20, 0),
    CD_AUTSC_SOLIC                NUMBER(20, 0),
    FG_RDA                        NUMBER(1, 0),
    FG_VINCULO_MANUAL             NUMBER(1, 0),
    CD_CARTAO_BNF_XML             VARCHAR2(20 CHAR),
    NR_CONSELHO_EXEC              VARCHAR2(15 CHAR),
    NR_CONSELHO_SOLIC             VARCHAR2(15 CHAR),
    DT_PRIMEIRA_CONSULTA          DATE,
    DS_PRIMEIRO_MOTIVO            VARCHAR2(75 CHAR),
    DS_SEGUNDO_MOTIVO             VARCHAR2(75 CHAR),
    CD_PRESTADOR_EXEC_CNPJ        NUMBER(14, 0),
    CD_PRESTADOR_EXEC_CPF         NUMBER(11, 0),
    FG_CLEANER                    NUMBER(1, 0),
    FG_ENVIO_PRODUCAO             NUMBER(1, 0),
    TP_BENEF                      NUMBER(1, 0),
    DM_TP_IDENT_BENEF             NUMBER(2, 0),
    CD_TOKEN_VALIDACAO            VARCHAR2(10 CHAR),
    DM_CD_AUSENCIA_VALID          VARCHAR2(10 CHAR),
    DS_TEMPLATE_BIOM              CLOB,
    DM_CD_ETAPA_AUTRIZ            NUMBER(1, 0),
    DS_IDENT_BENEF                CLOB,
    CD_PROFIS_SOLIC               NUMBER(20, 0),
    FG_CONVERSAO_PACOTE_CIRURGICO VARCHAR2(1 CHAR),
    DT_CARGA                      TIMESTAMP
) TABLESPACE TABS_DAT;


CREATE TABLE PRD_STG.ODS_DTC_CM_TISS_GUIA (
    CD_TISS_GUIA                  NUMBER(20, 0),
    TP_GUIA                       NUMBER(1, 0),
    NR_REG_ANS                    VARCHAR2(6 CHAR),
    NR_GUIA                       VARCHAR2(20 CHAR),
    NR_GUIA_PRINCIPAL             VARCHAR2(20 CHAR),
    DT_AUTORIZACAO                DATE,
    NR_SENHA                      VARCHAR2(20 CHAR),
    DT_VALIDADE_SENHA             DATE,
    DT_HR_EMISSAO                 DATE,
    DT_HR_INCLUSAO                DATE,
    CD_CARTAO_BNF                 VARCHAR2(21 CHAR),
    NM_PLANO_BNF                  VARCHAR2(60 CHAR),
    DT_VALIDADE_CARTEIRA_BNF      DATE,
    NM_COMPLETO_BNF               VARCHAR2(70 CHAR),
    NR_CNS_BNF                    VARCHAR2(20 CHAR),
    CD_PREST_SOLIC                NUMBER(20, 0),
    NM_PREST_SOLIC                VARCHAR2(70 CHAR),
    CD_CNES_SOLIC                 NUMBER(7, 0),
    NM_PROFIS_SOLIC               VARCHAR2(70 CHAR),
    TP_CONSELHO_SOLIC             VARCHAR2(7 CHAR),
    NR_CONSELHO_SOLIC_OLD         NUMBER(15, 0),
    SG_UF_CONSELHO_SOLIC          VARCHAR2(2 CHAR),
    CD_CBOS_SOLIC                 VARCHAR2(10 CHAR),
    DT_HR_SOLIC                   DATE,
    TP_ATENDIMENTO                VARCHAR2(2 CHAR),
    TP_CARATER                    VARCHAR2(1 CHAR),
    DS_INDICACAO_CLINICA          VARCHAR2(500 CHAR),
    CD_OPERADORA_EXEC             NUMBER,
    NM_OPERADORA_EXEC             VARCHAR2(70 CHAR),
    CD_CNES_OPERADORA_EXEC        NUMBER,
    CD_PRESTADOR_EXEC             NUMBER(14, 0),
    NM_PRESTADOR_EXEC             VARCHAR2(70 CHAR),
    TP_LOGRADOURO_EXEC            VARCHAR2(3 CHAR),
    DS_LOGRADOURO_EXEC            VARCHAR2(50 CHAR),
    NR_LOGRADOURO_EXEC            VARCHAR2(5 CHAR),
    DS_COMPLEMENTO_EXEC           VARCHAR2(40 CHAR),
    NM_MUNICIPIO_EXEC             VARCHAR2(120 CHAR),
    SG_UF_EXEC                    VARCHAR2(2 CHAR),
    CD_IBGE_MUNICIPIO_EXEC        VARCHAR2(7 CHAR),
    NR_CEP_EXEC                   VARCHAR2(8 CHAR),
    CD_CNES_EXEC                  VARCHAR2(7 CHAR),
    CD_PARTICIPACAO_EXEC          VARCHAR2(2 CHAR),
    NM_PROFISSIONAL_EXEC          VARCHAR2(70 CHAR),
    TP_CONSELHO_EXEC              VARCHAR2(7 CHAR),
    NR_CONSELHO_EXEC_OLD          NUMBER(15, 0),
    SG_UF_CONSELHO_EXEC           VARCHAR2(2 CHAR),
    NR_CPF_EXEC                   NUMBER(14, 0),
    CD_CBOS_EXEC                  VARCHAR2(10 CHAR),
    TP_DOENCA                     VARCHAR2(1 CHAR),
    NR_TMP_DOENCA                 NUMBER(3, 0),
    DM_TMP_DOENCA                 VARCHAR2(1 CHAR),
    TP_ACIDENTE                   NUMBER(1, 0),
    DT_HR_ATENDIMENTO             DATE,
    TP_CONSULTA                   VARCHAR2(1 CHAR),
    TP_SAIDA_CONSULTA             VARCHAR2(1 CHAR),
    DS_OBSERVACAO                 VARCHAR2(500 CHAR),
    VL_TOTAL_PROCEDIMENTO         NUMBER(9, 2),
    VL_TOTAL_TAXA_ALUGUEL         NUMBER(9, 2),
    VL_TOTAL_MATERIAL             NUMBER(9, 2),
    VL_TOTAL_MEDICAMENTO          NUMBER(9, 2),
    VL_TOTAL_DIARIA               NUMBER(9, 2),
    VL_TOTAL_TAXAS_DIVERSAS       NUMBER(9, 2),
    VL_TOTAL_GASES_MED            NUMBER(9, 2),
    VL_TOTAL_OPM                  NUMBER(9, 2),
    VL_TOTAL_GUIA                 NUMBER(9, 2),
    CD_MOTIVO_SAIDA               VARCHAR2(2 CHAR),
    NR_SOLIC                      NUMBER(20, 0),
    DT_HR_ALTA                    DATE,
    TP_ACOMODACAO                 NUMBER(2, 0),
    TP_OBSTET_GESTACAO            VARCHAR2(1 CHAR),
    TP_OBSTET_ABORTO              VARCHAR2(1 CHAR),
    TP_OBSTET_TRANST_MATERNO      VARCHAR2(1 CHAR),
    TP_OBSTET_COMPLIC_PUERPERIO   VARCHAR2(1 CHAR),
    TP_OBSTET_ATENDIMENTO_RN      VARCHAR2(1 CHAR),
    TP_OBSTET_COMPLIC_NEONATAL    VARCHAR2(1 CHAR),
    TP_OBSTET_BAIXO_PESO          VARCHAR2(1 CHAR),
    TP_OBSTET_CESAREA             VARCHAR2(1 CHAR),
    TP_OBSTET_NORMAL              VARCHAR2(1 CHAR),
    DM_CD_OBITO_MULHER            NUMBER(1, 0),
    QT_NASCIDO_VIVO               NUMBER(2, 0),
    QT_NASCIDO_PREMATURO          NUMBER(2, 0),
    NR_DECLARACAO_NASC_VIVO       VARCHAR2(15 CHAR),
    QT_OBITO_PRECOCE              NUMBER(2, 0),
    QT_OBITO_TARDIO               NUMBER(2, 0),
    QT_NASCIDO_MORTO              NUMBER(2, 0),
    TP_INTERNACAO                 NUMBER,
    NR_DECLARACAO_OBITO           VARCHAR2(12 CHAR),
    DM_REGIME_INTERNACAO          NUMBER(1, 0),
    DM_TP_FATURAMENTO             VARCHAR2(1 CHAR),
    DT_ENTRADA                    DATE,
    TP_ORIGEM                     NUMBER(1, 0),
    TP_SITUACAO                   NUMBER(2, 0),
    CD_LOCAL_ATENDIMENTO          NUMBER(20, 0),
    CD_USUARIO                    NUMBER(20, 0),
    CD_TISS_GUIA_PRINCIPAL        NUMBER(20, 0),
    CD_CARTAO_UNIMED_BNF          NUMBER(4, 0),
    CD_CARTAO_PLANO_BNF           NUMBER(4, 0),
    CD_CARTAO_BENEF_BNF           NUMBER(6, 0),
    CD_CARTAO_DEPEN_BNF           NUMBER(2, 0),
    DT_PROC_PRECIF                DATE,
    DT_PROC_AUDIT                 DATE,
    CD_GUIA_SCCARD                NUMBER(20, 0),
    CD_ARQUIVO_TISS               NUMBER(20, 0),
    CD_UNIMED_EXEC                NUMBER(4, 0),
    DT_PROC_CAMARA                DATE,
    DM_CLASSIFICACAO_SOLIC        NUMBER(5, 0),
    NR_SENHA_GESTAO               VARCHAR2(20 CHAR),
    DT_PROC_ENTREGA               DATE,
    FG_ALTERACAO                  NUMBER(1, 0),
    DT_AJUSTE_VIA_ACESSO          DATE,
    DT_TROCA_DESC_ITENS           DATE,
    NR_VERSAO_TISS                VARCHAR2(7 CHAR),
    FG_VALID_IMPORT_ATIVA         NUMBER(1, 0),
    FG_ATENDIMENTO_RN             VARCHAR2(1 CHAR),
    NR_GUIA_PRESTADOR             VARCHAR2(20 CHAR),
    FG_OBITO_RN                   VARCHAR2(1 CHAR),
    NR_VERSAO_GUIA_IMPORT         VARCHAR2(7 CHAR),
    CD_PROTOCOLO                  NUMBER,
    NR_LOTE                       NUMBER(20, 0),
    CD_AUTSC_SOLIC                NUMBER(20, 0),
    FG_RDA                        NUMBER(1, 0),
    FG_VINCULO_MANUAL             NUMBER(1, 0),
    CD_CARTAO_BNF_XML             VARCHAR2(20 CHAR),
    NR_CONSELHO_EXEC              VARCHAR2(15 CHAR),
    NR_CONSELHO_SOLIC             VARCHAR2(15 CHAR),
    DT_PRIMEIRA_CONSULTA          DATE,
    DS_PRIMEIRO_MOTIVO            VARCHAR2(75 CHAR),
    DS_SEGUNDO_MOTIVO             VARCHAR2(75 CHAR),
    CD_PRESTADOR_EXEC_CNPJ        NUMBER(14, 0),
    CD_PRESTADOR_EXEC_CPF         NUMBER(11, 0),
    FG_CLEANER                    NUMBER(1, 0),
    FG_ENVIO_PRODUCAO             NUMBER(1, 0),
    TP_BENEF                      NUMBER(1, 0),
    DM_TP_IDENT_BENEF             NUMBER(2, 0),
    CD_TOKEN_VALIDACAO            VARCHAR2(10 CHAR),
    DM_CD_AUSENCIA_VALID          VARCHAR2(10 CHAR),
    DS_TEMPLATE_BIOM              CLOB,
    DM_CD_ETAPA_AUTRIZ            NUMBER(1, 0),
    DS_IDENT_BENEF                CLOB,
    CD_PROFIS_SOLIC               NUMBER(20, 0),
    FG_CONVERSAO_PACOTE_CIRURGICO VARCHAR2(1 CHAR),
    DT_CARGA                      TIMESTAMP
) TABLESPACE TABS_DAT;